FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

COPY requirements-api.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements-api.txt

COPY common ./common
COPY gateway ./gateway
COPY executors ./executors
COPY main.py ./

ENV PORT=14564
EXPOSE 14564

CMD ["python", "main.py"]
